name: ng_values
description: Netguru Flutter Developer recruitment task.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: 4.0.5855
  provider: ^4.3.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_jagi: ^0.0.2

flutter:
  uses-material-design: true