name: ng_values
description: Netguru Flutter Developer recruitment task.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# Dependencies should be sorted alphabetically
dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+4
  http: ^0.12.2
  json_annotation: ^3.1.1
  material_design_icons_flutter: 4.0.5855
  provider: ^4.3.2+4
  shared_preferences: ^0.5.12+4

# Dependencies should be sorted alphabetically
dev_dependencies:
  build_runner: ^1.10.13
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  pedantic_jagi: ^0.0.2

flutter:
  uses-material-design: true